package jsonschema2go

import (
	"bytes"
	"context"
	"github.com/stretchr/testify/require"
	"go/format"
	"testing"
)

func TestImports_List(t *testing.T) {
	tests := []struct {
		name          string
		currentGoPath string
		importGoPaths []string
		wantImports   []Import
	}{
		{
			"empty",
			"github.com/jwilner/jsonschema2go",
			[]string{},
			nil,
		},
		{
			"alias",
			"github.com/jwilner/jsonschema2go",
			[]string{
				"github.com/jwilner/jsonschema2go/example",
				"github.com/jwilner/jsonschema2go/foo/example",
			},
			[]Import{
				{"github.com/jwilner/jsonschema2go/example", ""},
				{"github.com/jwilner/jsonschema2go/foo/example", "example2"},
			},
		},
		{
			"multiple",
			"github.com/jwilner/jsonschema2go",
			[]string{"encoding/json", "encoding/json"},
			[]Import{
				{"encoding/json", ""},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			require.Equal(t, tt.wantImports, newImports(tt.currentGoPath, tt.importGoPaths).List())
		})
	}
}

func TestImports_QualName(t *testing.T) {
	tests := []struct {
		name          string
		currentGoPath string
		importGoPaths []string
		typeInfo      TypeInfo
		want          string
	}{
		{
			"builtin",
			"github.com/jwilner/jsonschema2go",
			[]string{"github.com/jwilner/jsonschema2go/example", "github.com/jwilner/jsonschema2go/foo/example"},
			TypeInfo{Name: "int"},
			"int",
		},
		{
			"external",
			"github.com/jwilner/jsonschema2go",
			[]string{"github.com/jwilner/jsonschema2go/example", "github.com/jwilner/jsonschema2go/foo/example"},
			TypeInfo{GoPath: "github.com/jwilner/jsonschema2go", Name: "Bob"},
			"Bob",
		},
		{
			"external",
			"github.com/jwilner/jsonschema2go",
			[]string{"github.com/jwilner/jsonschema2go/example", "github.com/jwilner/jsonschema2go/foo/example"},
			TypeInfo{GoPath: "github.com/jwilner/jsonschema2go/example", Name: "Bob"},
			"example.Bob",
		},
		{
			"external with alias",
			"github.com/jwilner/jsonschema2go",
			[]string{"github.com/jwilner/jsonschema2go/example", "github.com/jwilner/jsonschema2go/foo/example"},
			TypeInfo{GoPath: "github.com/jwilner/jsonschema2go/foo/example", Name: "Bob"},
			"example2.Bob",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			require.Equal(t, tt.want, newImports(tt.currentGoPath, tt.importGoPaths).QualName(tt.typeInfo))
		})
	}
}

func TestPrintFile(t *testing.T) {
	errBit := `
type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
`

	tests := []struct {
		name    string
		goPath  string
		plans   []Plan
		wantW   string
		wantErr bool
	}{
		{
			name:   "simple struct",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&StructPlan{
					Comment: "Bob does lots of cool things",
					Fields: []StructField{
						{Name: "Count", Type: TypeInfo{Name: "int"}, Tag: `json:"count,omitempty"`},
					},
					typeInfo: TypeInfo{
						Name: "Bob",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"fmt"
)

// Bob does lots of cool things
type Bob struct {
	Count int ` + "`" + `json:"count,omitempty"` + "`" + `
}

func (m *Bob) Validate() error {
	return nil
}
` + errBit,
		},
		{
			name:   "struct with qualified field",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&StructPlan{
					Comment: "Bob does lots of cool things",
					Fields: []StructField{
						{Name: "Count", Type: TypeInfo{Name: "int"}, Tag: `json:"count,omitempty"`},
						{
							Name: "Other",
							Type: TypeInfo{
								GoPath: "github.com/jwilner/jsonschema2go/blah",
								Name:   "OtherType",
							},
							Tag: `json:"other,omitempty"`,
						},
					},
					typeInfo: TypeInfo{
						Name: "Bob",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"fmt"
	"github.com/jwilner/jsonschema2go/blah"
)

// Bob does lots of cool things
type Bob struct {
	Count int 				` + "`" + `json:"count,omitempty"` + "`" + `
	Other blah.OtherType 	` + "`" + `json:"other,omitempty"` + "`" + `
}

func (m *Bob) Validate() error {
	return nil
}

` + errBit,
		},
		{
			name:   "struct with aliased import",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&StructPlan{
					Comment: "Bob does lots of cool things",
					Fields: []StructField{
						{Name: "Count", Type: TypeInfo{Name: "int"}, Tag: `json:"count,omitempty"`},
						{
							Name: "Other",
							Type: TypeInfo{
								GoPath:  "github.com/jwilner/jsonschema2go/blah",
								Name:    "OtherType",
								Pointer: true,
							},
							Tag: `json:"other,omitempty"`,
						},
						{
							Name: "OtherOther",
							Type: TypeInfo{
								GoPath: "github.com/jwilner/jsonschema2go/bob/blah",
								Name:   "AnotherType",
							},
							Tag: `json:"another,omitempty"`,
						},
					},
					typeInfo: TypeInfo{
						Name: "Bob",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"fmt"
	"github.com/jwilner/jsonschema2go/blah"
	blah2 "github.com/jwilner/jsonschema2go/bob/blah"
)

// Bob does lots of cool things
type Bob struct {
	Count 		int 				` + "`" + `json:"count,omitempty"` + "`" + `
	Other 		*blah.OtherType 	` + "`" + `json:"other,omitempty"` + "`" + `
	OtherOther 	blah2.AnotherType 	` + "`" + `json:"another,omitempty"` + "`" + `
}

func (m *Bob) Validate() error {
	return nil
}

` + errBit,
		},
		{
			name:   "struct with embedded",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&StructPlan{
					Comment: "Bob does lots of cool things",
					Fields: []StructField{
						{
							Type: TypeInfo{
								GoPath: "github.com/jwilner/jsonschema2go/blah",
								Name:   "OtherType",
							},
						},
					},
					typeInfo: TypeInfo{
						Name: "Bob",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"fmt"
	"github.com/jwilner/jsonschema2go/blah"
)

// Bob does lots of cool things
type Bob struct {
	blah.OtherType
}

func (m *Bob) Validate() error {
	return nil
}

` + errBit,
		},
		{
			name:   "struct with embedded",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&StructPlan{
					Comment: "Bob does lots of cool things",
					Fields: []StructField{
						{
							Type: TypeInfo{
								GoPath: "github.com/jwilner/jsonschema2go",
								Name:   "OtherType",
							},
						},
					},
					typeInfo: TypeInfo{
						Name: "Bob",
					},
				},
				&StructPlan{
					Comment: "OtherType does lots of cool things",
					Fields: []StructField{
						{Type: TypeInfo{Name: "int"}, Name: "Count", Tag: `json:"count,omitempty"`},
					},
					typeInfo: TypeInfo{
						Name: "OtherType",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"fmt"
)

// Bob does lots of cool things
type Bob struct {
	OtherType
}

func (m *Bob) Validate() error {
	return nil
}

// OtherType does lots of cool things
type OtherType struct {
	Count int ` + "`" + `json:"count,omitempty"` + "`" + `
}

func (m *OtherType) Validate() error {
	return nil
}

` + errBit,
		},
		{
			name:   "array with struct",
			goPath: "github.com/jwilner/jsonschema2go",
			plans: []Plan{
				&SlicePlan{
					typeInfo: TypeInfo{
						Name: "Bob",
					},
					Comment: "Bob does lots of cool things",
					ItemType: TypeInfo{
						GoPath: "github.com/jwilner/jsonschema2go",
						Name:   "OtherType",
					},
				},
				&StructPlan{
					Comment: "OtherType does lots of cool things",
					Fields: []StructField{
						{Type: TypeInfo{Name: "int"}, Name: "Count", Tag: `json:"count,omitempty"`},
					},
					typeInfo: TypeInfo{
						Name: "OtherType",
					},
				},
			},
			wantW: `
// Code generated by jsonschema2go. DO NOT EDIT.
package jsonschema2go

import (
	"encoding/json"
	"fmt"
)

// OtherType does lots of cool things
type OtherType struct {
	Count int ` + "`" + `json:"count,omitempty"` + "`" + `
}

func (m *OtherType) Validate() error {
	return nil
}

// Bob does lots of cool things
type Bob []OtherType

func (m Bob) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte(` + "`[]`" + `), nil
	}
	return json.Marshal([]OtherType(m))
}

func (m Bob) Validate() error {
	return nil
}

` + errBit,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var w bytes.Buffer
			err := newPrinter(nil).Print(context.Background(), &w, tt.goPath, tt.plans)
			if (err != nil) != tt.wantErr {
				t.Fatalf("printStruct() error = %v, wantErr %v", err, tt.wantErr)
			}
			formatted, err := format.Source(w.Bytes())
			if err != nil {
				t.Fatalf("unable to format: %v", err)
			}
			formattedWant, err := format.Source([]byte(tt.wantW))
			if err != nil {
				t.Fatalf("unable to format wanted: %v", err)
			}
			require.Equal(t, string(formattedWant), string(formatted))
		})
	}
}
