// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
	"github.com/ns1/jsonschema2go/internal/composite/testdata/generate/multi_pkg/foobar"
)

// Bar is generated from https://example.com/testdata/generate/multi_pkg/foo/bar.json
// Bar gives you some dumb info
type Bar struct {
	Name *string `json:"name,omitempty"`
	foobar.Blob
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/multi_pkg/foo/bar.json
func (m *Bar) Validate() error {
	if err := m.Blob.Validate(); err != nil {
		return err
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
