// Code generated by jsonschema2go. DO NOT EDIT.
package foobar

import (
	"fmt"
)

type Blob struct {
	Count int `json:"count,omitempty"`
}

func (m *Blob) Validate() error {
	return nil
}

type BlobValidationError struct {
	errType, jsonField, field, message string
}

func (e *BlobValidationError) ErrType() string {
	return e.errType
}

func (e *BlobValidationError) JSONField() string {
	return e.jsonField
}

func (e *BlobValidationError) Field() string {
	return e.field
}

func (e *BlobValidationError) Message() string {
	return e.message
}

func (e *BlobValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}
