// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

// Bar gives you some dumb info
// generated from https://example.com/testdata/generate/composite/foo/bar.json
type Bar struct {
	Name *string `json:"name,omitempty"`
	ExplicitNameStruct
}

func (m *Bar) Validate() error {
	if err := m.ExplicitNameStruct.Validate(); err != nil {
		return err
	}
	return nil
}

// generated from https://example.com/testdata/generate/composite/foo/other.json
type ExplicitNameStruct struct {
	Count *int64 `json:"count,omitempty"`
}

func (m *ExplicitNameStruct) Validate() error {
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
