// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
	"github.com/jwilner/jsonschema2go/boxed"
)

// generated from https://example.com/testdata/render/array_field/foo/example.json
type Example struct {
	Options ExampleOptions `json:"options,omitempty"`
}

func (m *Example) Validate() error {
	if err := m.Options.Validate(); err != nil {
		return err
	}
	return nil
}

type ExampleValidationError struct {
	errType, jsonField, field, message string
}

func (e *ExampleValidationError) ErrType() string {
	return e.errType
}

func (e *ExampleValidationError) JSONField() string {
	return e.jsonField
}

func (e *ExampleValidationError) Field() string {
	return e.field
}

func (e *ExampleValidationError) Message() string {
	return e.message
}

func (e *ExampleValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}

// generated from https://example.com/testdata/render/array_field/foo/inner.json
type Inner struct {
	Name  boxed.String `json:"name"`
	Value interface{}  `json:"value,omitempty"`
}

func (m *Inner) Validate() error {
	return nil
}

func (m *Inner) MarshalJSON() ([]byte, error) {
	inner := struct {
		Name  *string     `json:"name,omitempty"`
		Value interface{} `json:"value,omitempty"`
	}{
		Value: m.Value,
	}
	if m.Name.Set {
		inner.Name = &m.Name.String
	}
	return json.Marshal(inner)
}

type InnerValidationError struct {
	errType, jsonField, field, message string
}

func (e *InnerValidationError) ErrType() string {
	return e.errType
}

func (e *InnerValidationError) JSONField() string {
	return e.jsonField
}

func (e *InnerValidationError) Field() string {
	return e.field
}

func (e *InnerValidationError) Message() string {
	return e.message
}

func (e *InnerValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}

// generated from https://example.com/testdata/render/array_field/foo/example.json#/properties/options
type ExampleOptions []Inner

func (m ExampleOptions) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte(`[]`), nil
	}
	return json.Marshal([]Inner(m))
}

func (m ExampleOptions) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

type ExampleOptionsValidationError struct {
	errType, jsonField, field, message string
}

func (e *ExampleOptionsValidationError) ErrType() string {
	return e.errType
}

func (e *ExampleOptionsValidationError) JSONField() string {
	return e.jsonField
}

func (e *ExampleOptionsValidationError) Field() string {
	return e.field
}

func (e *ExampleOptionsValidationError) Message() string {
	return e.message
}

func (e *ExampleOptionsValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}
