// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
	"github.com/jwilner/jsonschema2go/boxed"
)

// Bar gives you some dumb info
type Bar struct {
	Bar boxed.Int64  `json:"bar"`
	Foo boxed.String `json:"foo"`
}

func (m *Bar) Validate() error {
	if !m.Bar.Set {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Bar"},
			jsonPath: []interface{}{"bar"},
		}
	}
	if !m.Foo.Set {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Foo"},
			jsonPath: []interface{}{"foo"},
		}
	}
	return nil
}

func (m *Bar) MarshalJSON() ([]byte, error) {
	inner := struct {
		Bar *int64  `json:"bar,omitempty"`
		Foo *string `json:"foo,omitempty"`
	}{}
	if m.Bar.Set {
		inner.Bar = &m.Bar.Int64
	}
	if m.Foo.Set {
		inner.Foo = &m.Foo.String
	}
	return json.Marshal(inner)
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
