// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

// Bar is generated from https://example.com/testdata/generate/composite_validation/foo/bar.json
// Bar gives you some dumb info
type Bar struct {
	_ []byte
	Blob
	Baz
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/composite_validation/foo/bar.json
func (m *Bar) Validate() error {
	if err := m.Blob.Validate(); err != nil {
		return err
	}
	if err := m.Baz.Validate(); err != nil {
		return err
	}
	return nil
}

// Baz is generated from https://example.com/testdata/generate/composite_validation/foo/baz.json
type Baz struct {
	_    []byte
	Name *string `json:"name,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/composite_validation/foo/baz.json
func (m *Baz) Validate() error {
	if m.Name == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Name"},
			jsonPath: []interface{}{"name"},
		}
	}
	return nil
}

// Blob is generated from https://example.com/testdata/generate/composite_validation/foo/blob.json
type Blob struct {
	_     []byte
	Count *int64 `json:"count,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/composite_validation/foo/blob.json
func (m *Blob) Validate() error {
	if m.Count == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Count"},
			jsonPath: []interface{}{"count"},
		}
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
