// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
	"github.com/jwilner/jsonschema2go/boxed"
)

// Bar gives you some dumb info
type Bar struct {
	Direction interface{}
}

func (m *Bar) Validate() error {
	return nil
}

func (m *Bar) UnmarshalJSON(data []byte) error {
	var discrim struct {
		Direction string `json:"direction"`
	}
	if err := json.Unmarshal(data, &discrim); err != nil {
		return err
	}
	switch discrim.Direction {
	case "l":
		m.Direction = new(Left)
	case "r":
		m.Direction = new(Right)
	default:
		return fmt.Errorf("unknown discriminator: %v", discrim.Direction)
	}
	return json.Unmarshal(data, m.Direction)
}

func (m *Bar) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.Direction)
}

type BarValidationError struct {
	errType, jsonField, field, message string
}

func (e *BarValidationError) ErrType() string {
	return e.errType
}

func (e *BarValidationError) JSONField() string {
	return e.jsonField
}

func (e *BarValidationError) Field() string {
	return e.field
}

func (e *BarValidationError) Message() string {
	return e.message
}

func (e *BarValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}

type Left struct {
	Direction boxed.String `json:"direction"`
	Value     boxed.Int64  `json:"value"`
}

func (m *Left) Validate() error {
	return nil
}

func (m *Left) MarshalJSON() ([]byte, error) {
	inner := struct {
		Direction *string `json:"direction,omitempty"`
		Value     *int64  `json:"value,omitempty"`
	}{}
	if m.Direction.Set {
		inner.Direction = &m.Direction.String
	}
	if m.Value.Set {
		inner.Value = &m.Value.Int64
	}
	return json.Marshal(inner)
}

type LeftValidationError struct {
	errType, jsonField, field, message string
}

func (e *LeftValidationError) ErrType() string {
	return e.errType
}

func (e *LeftValidationError) JSONField() string {
	return e.jsonField
}

func (e *LeftValidationError) Field() string {
	return e.field
}

func (e *LeftValidationError) Message() string {
	return e.message
}

func (e *LeftValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}

type Right struct {
	Direction boxed.String  `json:"direction"`
	Value     boxed.Float64 `json:"value"`
}

func (m *Right) Validate() error {
	return nil
}

func (m *Right) MarshalJSON() ([]byte, error) {
	inner := struct {
		Direction *string  `json:"direction,omitempty"`
		Value     *float64 `json:"value,omitempty"`
	}{}
	if m.Direction.Set {
		inner.Direction = &m.Direction.String
	}
	if m.Value.Set {
		inner.Value = &m.Value.Float64
	}
	return json.Marshal(inner)
}

type RightValidationError struct {
	errType, jsonField, field, message string
}

func (e *RightValidationError) ErrType() string {
	return e.errType
}

func (e *RightValidationError) JSONField() string {
	return e.jsonField
}

func (e *RightValidationError) Field() string {
	return e.field
}

func (e *RightValidationError) Message() string {
	return e.message
}

func (e *RightValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}
