// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

// Bar is generated from https://example.com/testdata/generate/enum_field/foo/bar.json
// Bar gives you some dumb info
type Bar struct {
	Bar BarBar `json:"bar"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/enum_field/foo/bar.json
func (m *Bar) Validate() error {
	if err := m.Bar.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Bar"}, err.Path()...),
				jsonPath: append([]interface{}{"bar"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// BarBar is generated from https://example.com/testdata/generate/enum_field/foo/bar.json#/properties/bar
type BarBar []string

var (
	barBarItemsEnum = map[string]bool{"A": true, "B": true, "C": true}
)

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/enum_field/foo/bar.json#/properties/bar
func (m BarBar) Validate() error {
	for i := range m {
		if !barBarItemsEnum[m[i]] {
			return &validationError{
				errType:  "enum",
				message:  fmt.Sprintf(`must be one of ("A", "B", "C") but got %v`, m[i]),
				path:     []interface{}{i},
				jsonPath: []interface{}{i},
			}
		}
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
