// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

type Letter string

const (
	LetterA Letter = "a"
	LetterB Letter = "b"
	LetterC Letter = "c"
)

func (m Letter) Validate() error {
	switch m {
	case LetterA:
		return nil
	case LetterB:
		return nil
	case LetterC:
		return nil
	}
	return fmt.Errorf("unknown Letter: %v", m)
}

type validationError struct {
	errType, jsonField, field, message string
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONField() string {
	return e.jsonField
}

func (e *validationError) Field() string {
	return e.field
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}
