// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

type Letter string

const (
	LetterA Letter = "a"
	LetterB Letter = "b"
	LetterC Letter = "c"
)

func (m Letter) Validate() error {
	switch m {
	case LetterA:
		return nil
	case LetterB:
		return nil
	case LetterC:
		return nil
	}
	return fmt.Errorf("unknown Letter: %v", m)
}
