// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
	"github.com/ns1/jsonschema2go/internal/composite/testdata/generate/exclude_external_pkg/other"
)

// Bar is generated from https://example.com/testdata/generate/exclude_external_pkg/foo/example.json
// Bar gives you some dumb info
type Bar struct {
	_     []byte
	Inner *other.Excluded `json:"inner,omitempty"`
	Name  *string         `json:"name,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/exclude_external_pkg/foo/example.json
func (m *Bar) Validate() error {
	if m.Inner != nil {
		if err := m.Inner.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"Inner"}, err.Path()...),
					jsonPath: append([]interface{}{"inner"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
