// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
	"regexp"
)

// AddressDetails is generated from https://example.com/testdata/generate/complex/foo/address-details.json
type AddressDetails struct {
	_      [0]byte
	Name   *string `json:"name,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/address-details.json
func (m *AddressDetails) Validate() error {
	return nil
}

// DhcpOption is generated from https://example.com/testdata/generate/complex/foo/dhcp-option.json
type DhcpOption struct {
	_          [0]byte
	AlwaysSend *bool       `json:"always_send,omitempty"`
	Name       *string     `json:"name,omitempty"`
	Value      interface{} `json:"value,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-option.json
func (m *DhcpOption) Validate() error {
	if m.Name == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Name"},
			jsonPath: []interface{}{"name"},
		}
	}
	if m.Value == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Value"},
			jsonPath: []interface{}{"value"},
		}
	}
	return nil
}

// DhcpScopeGroupSettingsCommon is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-common.json
type DhcpScopeGroupSettingsCommon struct {
	_                 [0]byte
	Enabled           *bool                               `json:"enabled,omitempty"`
	Options           DhcpScopeGroupSettingsCommonOptions `json:"options"`
	RebindTimerSecs   *int64                              `json:"rebind_timer_secs,omitempty"`
	RenewTimerSecs    *int64                              `json:"renew_timer_secs,omitempty"`
	ValidLifetimeSecs *int64                              `json:"valid_lifetime_secs,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-common.json
func (m *DhcpScopeGroupSettingsCommon) Validate() error {
	if err := m.Options.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Options"}, err.Path()...),
				jsonPath: append([]interface{}{"options"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// DhcpScopeGroupSettingsSynthesizeDnsRecords is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-synthesize-dns-records.json
type DhcpScopeGroupSettingsSynthesizeDnsRecords struct {
	_                [0]byte
	Enabled          *bool   `json:"enabled,omitempty"`
	GeneratedPrefix  *string `json:"generated_prefix,omitempty"`
	QualifyingSuffix *string `json:"qualifying_suffix,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-synthesize-dns-records.json
func (m *DhcpScopeGroupSettingsSynthesizeDnsRecords) Validate() error {
	return nil
}

// DhcpScopeGroupSettingsV4 is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v4.json
type DhcpScopeGroupSettingsV4 struct {
	_ [0]byte
	DhcpScopeGroupSettingsCommon
	DhcpScopeGroupSettingsV4AllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v4.json
func (m *DhcpScopeGroupSettingsV4) Validate() error {
	if err := m.DhcpScopeGroupSettingsCommon.Validate(); err != nil {
		return err
	}
	if err := m.DhcpScopeGroupSettingsV4AllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// DhcpScopeGroupSettingsV4AllOf1 is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v4.json#/allOf/1
type DhcpScopeGroupSettingsV4AllOf1 struct {
	_                    [0]byte
	EchoClientID         *bool                                       `json:"echo_client_id,omitempty"`
	SynthesizeDnsRecords *DhcpScopeGroupSettingsSynthesizeDnsRecords `json:"synthesize_dns_records,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v4.json#/allOf/1
func (m *DhcpScopeGroupSettingsV4AllOf1) Validate() error {
	if m.SynthesizeDnsRecords != nil {
		if err := m.SynthesizeDnsRecords.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"SynthesizeDnsRecords"}, err.Path()...),
					jsonPath: append([]interface{}{"synthesize_dns_records"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// DhcpScopeGroupSettingsV6 is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v6.json
type DhcpScopeGroupSettingsV6 struct {
	_ [0]byte
	DhcpScopeGroupSettingsCommon
	DhcpScopeGroupSettingsV6AllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v6.json
func (m *DhcpScopeGroupSettingsV6) Validate() error {
	if err := m.DhcpScopeGroupSettingsCommon.Validate(); err != nil {
		return err
	}
	if err := m.DhcpScopeGroupSettingsV6AllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// DhcpScopeGroupSettingsV6AllOf1 is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v6.json#/allOf/1
type DhcpScopeGroupSettingsV6AllOf1 struct {
	_                     [0]byte
	PreferredLifetimeSecs *int64                                      `json:"preferred_lifetime_secs,omitempty"`
	SynthesizeDnsRecords  *DhcpScopeGroupSettingsSynthesizeDnsRecords `json:"synthesize_dns_records,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-v6.json#/allOf/1
func (m *DhcpScopeGroupSettingsV6AllOf1) Validate() error {
	if m.SynthesizeDnsRecords != nil {
		if err := m.SynthesizeDnsRecords.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"SynthesizeDnsRecords"}, err.Path()...),
					jsonPath: append([]interface{}{"synthesize_dns_records"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ExpandedReservation is generated from https://example.com/testdata/generate/complex/foo/expanded-reservation.json
type ExpandedReservation struct {
	_ [0]byte
	Reservation
	ExpandedReservationAllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-reservation.json
func (m *ExpandedReservation) Validate() error {
	if err := m.Reservation.Validate(); err != nil {
		return err
	}
	if err := m.ExpandedReservationAllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// ExpandedReservationAllOf1 is generated from https://example.com/testdata/generate/complex/foo/expanded-reservation.json#/allOf/1
type ExpandedReservationAllOf1 struct {
	_              [0]byte
	AddressDetails *AddressDetails `json:"address_details,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-reservation.json#/allOf/1
func (m *ExpandedReservationAllOf1) Validate() error {
	if m.AddressDetails != nil {
		if err := m.AddressDetails.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"AddressDetails"}, err.Path()...),
					jsonPath: append([]interface{}{"address_details"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ExpandedScope is generated from https://example.com/testdata/generate/complex/foo/expanded-scope.json
type ExpandedScope struct {
	_ [0]byte
	Scope
	ExpandedScopeAllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope.json
func (m *ExpandedScope) Validate() error {
	if err := m.Scope.Validate(); err != nil {
		return err
	}
	if err := m.ExpandedScopeAllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// ExpandedScopeAllOf1 is generated from https://example.com/testdata/generate/complex/foo/expanded-scope.json#/allOf/1
type ExpandedScopeAllOf1 struct {
	_              [0]byte
	AddressDetails *AddressDetails `json:"address_details,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope.json#/allOf/1
func (m *ExpandedScopeAllOf1) Validate() error {
	if m.AddressDetails != nil {
		if err := m.AddressDetails.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"AddressDetails"}, err.Path()...),
					jsonPath: append([]interface{}{"address_details"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ExpandedScopeGroupResponse is generated from https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json
type ExpandedScopeGroupResponse struct {
	_ [0]byte
	ScopeGroupResponse
	ExpandedScopeGroupResponseAllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json
func (m *ExpandedScopeGroupResponse) Validate() error {
	if err := m.ScopeGroupResponse.Validate(); err != nil {
		return err
	}
	if err := m.ExpandedScopeGroupResponseAllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// ExpandedScopeGroupResponseAllOf1 is generated from https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1
type ExpandedScopeGroupResponseAllOf1 struct {
	_            [0]byte
	Reservations ExpandedScopeGroupResponseAllOf1Reservations `json:"reservations"`
	Scopes       ExpandedScopeGroupResponseAllOf1Scopes       `json:"scopes"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1
func (m *ExpandedScopeGroupResponseAllOf1) Validate() error {
	if err := m.Reservations.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Reservations"}, err.Path()...),
				jsonPath: append([]interface{}{"reservations"}, err.JSONPath()...),
			}
		}
		return err
	}
	if err := m.Scopes.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Scopes"}, err.Path()...),
				jsonPath: append([]interface{}{"scopes"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// Reservation is generated from https://example.com/testdata/generate/complex/foo/reservation.json
type Reservation struct {
	_ [0]byte
	ReservationAllOf0
	ReservationFields
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/reservation.json
func (m *Reservation) Validate() error {
	if m.ID == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"ID"},
			jsonPath: []interface{}{"id"},
		}
	}
	if err := m.ReservationAllOf0.Validate(); err != nil {
		return err
	}
	if err := m.ReservationFields.Validate(); err != nil {
		return err
	}
	return nil
}

// ReservationAllOf0 is generated from https://example.com/testdata/generate/complex/foo/reservation.json#/allOf/0
type ReservationAllOf0 struct {
	_  [0]byte
	ID *int64 `json:"id,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/reservation.json#/allOf/0
func (m *ReservationAllOf0) Validate() error {
	return nil
}

// ReservationFields is generated from https://example.com/testdata/generate/complex/foo/reservation-fields.json
type ReservationFields struct {
	_            [0]byte
	AddressID    *int64                   `json:"address_id,omitempty"`
	Dhcpv6       *bool                    `json:"dhcpv6,omitempty"`
	Mac          *string                  `json:"mac,omitempty"`
	Options      ReservationFieldsOptions `json:"options"`
	ScopeGroupID *int64                   `json:"scope_group_id,omitempty"`
}

var (
	reservationFieldsMacPattern = regexp.MustCompile(`^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`)
)

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/reservation-fields.json
func (m *ReservationFields) Validate() error {
	if m.Options == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Options"},
			jsonPath: []interface{}{"options"},
		}
	}
	if m.Mac != nil && !reservationFieldsMacPattern.MatchString(*m.Mac) {
		return &validationError{
			errType:  "pattern",
			path:     []interface{}{"Mac"},
			jsonPath: []interface{}{"mac"},
			message:  fmt.Sprintf(`must match '^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$' but got %q`, *m.Mac),
		}
	}
	if err := m.Options.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Options"}, err.Path()...),
				jsonPath: append([]interface{}{"options"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// Scope is generated from https://example.com/testdata/generate/complex/foo/scope.json
type Scope struct {
	_ [0]byte
	ScopeAllOf0
	ScopeFields
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope.json
func (m *Scope) Validate() error {
	if err := m.ScopeAllOf0.Validate(); err != nil {
		return err
	}
	if err := m.ScopeFields.Validate(); err != nil {
		return err
	}
	return nil
}

// ScopeAllOf0 is generated from https://example.com/testdata/generate/complex/foo/scope.json#/allOf/0
type ScopeAllOf0 struct {
	_  [0]byte
	ID *int64 `json:"id,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope.json#/allOf/0
func (m *ScopeAllOf0) Validate() error {
	return nil
}

// ScopeFields is generated from https://example.com/testdata/generate/complex/foo/scope-fields.json
type ScopeFields struct {
	_                 [0]byte
	AddressID         *int64             `json:"address_id,omitempty"`
	Options           ScopeFieldsOptions `json:"options"`
	ScopeGroupID      *int64             `json:"scope_group_id,omitempty"`
	ValidLifetimeSecs *int64             `json:"valid_lifetime_secs,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope-fields.json
func (m *ScopeFields) Validate() error {
	if m.AddressID == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"AddressID"},
			jsonPath: []interface{}{"address_id"},
		}
	}
	if m.Options == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Options"},
			jsonPath: []interface{}{"options"},
		}
	}
	if err := m.Options.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"Options"}, err.Path()...),
				jsonPath: append([]interface{}{"options"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// ScopeGroupResponse is generated from https://example.com/testdata/generate/complex/foo/scope-group-response.json
type ScopeGroupResponse struct {
	_ [0]byte
	ScopeGroupUpdateable
	ScopeGroupResponseAllOf1
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope-group-response.json
func (m *ScopeGroupResponse) Validate() error {
	if m.Dhcpv4 == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Dhcpv4"},
			jsonPath: []interface{}{"dhcpv4"},
		}
	}
	if m.Dhcpv6 == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Dhcpv6"},
			jsonPath: []interface{}{"dhcpv6"},
		}
	}
	if m.ID == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"ID"},
			jsonPath: []interface{}{"id"},
		}
	}
	if m.Name == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"Name"},
			jsonPath: []interface{}{"name"},
		}
	}
	if err := m.ScopeGroupUpdateable.Validate(); err != nil {
		return err
	}
	if err := m.ScopeGroupResponseAllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// ScopeGroupResponseAllOf1 is generated from https://example.com/testdata/generate/complex/foo/scope-group-response.json#/allOf/1
type ScopeGroupResponseAllOf1 struct {
	_         [0]byte
	ID        *int64 `json:"id,omitempty"`
	NetworkID *int64 `json:"network_id,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope-group-response.json#/allOf/1
func (m *ScopeGroupResponseAllOf1) Validate() error {
	return nil
}

// ScopeGroupUpdateable is generated from https://example.com/testdata/generate/complex/foo/scope-group-updateable.json
type ScopeGroupUpdateable struct {
	_             [0]byte
	DhcpServiceID *int64                    `json:"dhcp_service_id,omitempty"`
	Dhcpv4        *DhcpScopeGroupSettingsV4 `json:"dhcpv4,omitempty"`
	Dhcpv6        *DhcpScopeGroupSettingsV6 `json:"dhcpv6,omitempty"`
	Name          *string                   `json:"name,omitempty"`
	ReverseDns    *bool                     `json:"reverse_dns,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope-group-updateable.json
func (m *ScopeGroupUpdateable) Validate() error {
	if m.Dhcpv4 != nil {
		if err := m.Dhcpv4.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"Dhcpv4"}, err.Path()...),
					jsonPath: append([]interface{}{"dhcpv4"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	if m.Dhcpv6 != nil {
		if err := m.Dhcpv6.Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{"Dhcpv6"}, err.Path()...),
					jsonPath: append([]interface{}{"dhcpv6"}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// DhcpScopeGroupSettingsCommonOptions is generated from https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-common.json#/properties/options
type DhcpScopeGroupSettingsCommonOptions []*DhcpOption

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/dhcp-scope-group-settings-common.json#/properties/options
func (m DhcpScopeGroupSettingsCommonOptions) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ExpandedScopeGroupResponseAllOf1Reservations is generated from https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1/properties/reservations
type ExpandedScopeGroupResponseAllOf1Reservations []*ExpandedReservation

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1/properties/reservations
func (m ExpandedScopeGroupResponseAllOf1Reservations) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ExpandedScopeGroupResponseAllOf1Scopes is generated from https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1/properties/scopes
type ExpandedScopeGroupResponseAllOf1Scopes []*ExpandedScope

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/expanded-scope-group-response.json#/allOf/1/properties/scopes
func (m ExpandedScopeGroupResponseAllOf1Scopes) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ReservationFieldsOptions is generated from https://example.com/testdata/generate/complex/foo/reservation-fields.json#/properties/options
// the options assigned to this reservation
type ReservationFieldsOptions []*DhcpOption

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/reservation-fields.json#/properties/options
func (m ReservationFieldsOptions) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

// ScopeFieldsOptions is generated from https://example.com/testdata/generate/complex/foo/scope-fields.json#/properties/options
// the options assigned to this scope
type ScopeFieldsOptions []*DhcpOption

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/complex/foo/scope-fields.json#/properties/options
func (m ScopeFieldsOptions) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
