// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
	"github.com/jwilner/jsonschema2go/pkg/boxed"
	"regexp"
)

// Bar gives you some dumb info
type Bar struct {
	Name boxed.String `json:"name"`
}

var (
	barNamePattern = regexp.MustCompile(`^[0-9]+$`)
)

func (m *Bar) Validate() error {
	if m.Name.Set && !barNamePattern.MatchString(m.Name.String) {
		return &validationError{
			errType:  "pattern",
			path:     []interface{}{"Name"},
			jsonPath: []interface{}{"name"},
			message:  fmt.Sprintf("must match '^[0-9]+$' but got %q", m.Name.String),
		}
	}
	return nil
}

func (m *Bar) MarshalJSON() ([]byte, error) {
	inner := struct {
		Name *string `json:"name,omitempty"`
	}{}
	if m.Name.Set {
		inner.Name = &m.Name.String
	}
	return json.Marshal(inner)
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
