// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
)

// Bar gives you some dumb info
// generated from https://example.com/testdata/generate/array/foo/bar.json
type Bar struct {
	Name *string `json:"name,omitempty"`
}

func (m *Bar) Validate() error {
	return nil
}

// Barz gives you lots of dumb info
// generated from https://example.com/testdata/generate/array/foo/barz.json
type Barz []Bar

func (m Barz) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte(`[]`), nil
	}
	return json.Marshal([]Bar(m))
}

func (m Barz) Validate() error {
	for i := range m {
		if err := m[i].Validate(); err != nil {
			if err, ok := err.(valErr); ok {
				return &validationError{
					errType:  err.ErrType(),
					message:  err.Message(),
					path:     append([]interface{}{i}, err.Path()...),
					jsonPath: append([]interface{}{i}, err.JSONPath()...),
				}
			}
			return err
		}
	}
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
