// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

// generated from https://example.com/testdata/generate/string_enum/foo/letter.json
type Letter string

const (
	LetterA Letter = "a"
	LetterB Letter = "b"
	LetterC Letter = "c"
)

func (m Letter) Validate() error {
	switch m {
	case LetterA:
		return nil
	case LetterB:
		return nil
	case LetterC:
		return nil
	}
	return &validationError{
		errType: "unknown_member",
		message: fmt.Sprintf("unknown value provided for Letter: %v", m),
	}
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
