// Code generated by jsonschema2go. DO NOT EDIT.
package foobar

import (
	"fmt"
)

// Blob is generated from https://example.com/testdata/generate/multi_pkg/foobar/blob.json
type Blob struct {
	_     []byte
	Count *int64 `json:"count,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/multi_pkg/foobar/blob.json
func (m *Blob) Validate() error {
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
