// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
)

// Bar gives you some dumb info
// generated from https://example.com/testdata/generate/array_all_of/foo/bar.json
type Bar struct {
	BarAllOf0
	BarAllOf1
}

func (m *Bar) Validate() error {
	if err := m.BarAllOf0.Validate(); err != nil {
		return err
	}
	if err := m.BarAllOf1.Validate(); err != nil {
		return err
	}
	return nil
}

// generated from https://example.com/testdata/generate/array_all_of/foo/bar.json#/allOf/0
type BarAllOf0 struct {
	ID *int64 `json:"id,omitempty"`
}

func (m *BarAllOf0) Validate() error {
	return nil
}

// generated from https://example.com/testdata/generate/array_all_of/foo/bar.json#/allOf/1
type BarAllOf1 struct {
	Name *string `json:"name,omitempty"`
}

func (m *BarAllOf1) Validate() error {
	return nil
}

// Barz gives you lots of dumb info
// generated from https://example.com/testdata/generate/array_all_of/foo/barz.json
type Barz []Bar

func (m Barz) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte(`[]`), nil
	}
	return json.Marshal([]Bar(m))
}

func (m Barz) Validate() error {
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
