// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"fmt"
)

// A is generated from https://example.com/testdata/generate/simple_nested/foo/a.json
type A struct {
	B *AB `json:"b,omitempty"`
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/simple_nested/foo/a.json
func (m *A) Validate() error {
	if m.B == nil {
		return &validationError{
			errType:  "required",
			message:  "field required",
			path:     []interface{}{"B"},
			jsonPath: []interface{}{"b"},
		}
	}
	if err := m.B.Validate(); err != nil {
		if err, ok := err.(valErr); ok {
			return &validationError{
				errType:  err.ErrType(),
				message:  err.Message(),
				path:     append([]interface{}{"B"}, err.Path()...),
				jsonPath: append([]interface{}{"b"}, err.JSONPath()...),
			}
		}
		return err
	}
	return nil
}

// AB is generated from https://example.com/testdata/generate/simple_nested/foo/a.json#/properties/b
type AB struct {
}

// Validate returns an error if this value is invalid according to rules defined in https://example.com/testdata/generate/simple_nested/foo/a.json#/properties/b
func (m *AB) Validate() error {
	return nil
}

type valErr interface {
	ErrType() string
	JSONPath() []interface{}
	Path() []interface{}
	Message() string
}

type validationError struct {
	errType, message string
	jsonPath, path   []interface{}
}

func (e *validationError) ErrType() string {
	return e.errType
}

func (e *validationError) JSONPath() []interface{} {
	return e.jsonPath
}

func (e *validationError) Path() []interface{} {
	return e.path
}

func (e *validationError) Message() string {
	return e.message
}

func (e *validationError) Error() string {
	return fmt.Sprintf("%v: %v", e.path, e.message)
}

var _ valErr = new(validationError)
