// Code generated by jsonschema2go. DO NOT EDIT.
package foo

import (
	"encoding/json"
	"fmt"
	"github.com/jwilner/jsonschema2go/boxed"
	"github.com/jwilner/jsonschema2go/internal/testdata/render/exclude_external_pkg/other"
)

// Bar gives you some dumb info
type Bar struct {
	Inner other.Excluded `json:"inner,omitempty"`
	Name  boxed.String   `json:"name"`
}

func (m *Bar) Validate() error {
	if err := m.Inner.Validate(); err != nil {
		return err
	}
	return nil
}

func (m *Bar) MarshalJSON() ([]byte, error) {
	inner := struct {
		Inner other.Excluded `json:"inner,omitempty"`
		Name  *string        `json:"name,omitempty"`
	}{
		Inner: m.Inner,
	}
	if m.Name.Set {
		inner.Name = &m.Name.String
	}
	return json.Marshal(inner)
}

type BarValidationError struct {
	errType, jsonField, field, message string
}

func (e *BarValidationError) ErrType() string {
	return e.errType
}

func (e *BarValidationError) JSONField() string {
	return e.jsonField
}

func (e *BarValidationError) Field() string {
	return e.field
}

func (e *BarValidationError) Message() string {
	return e.message
}

func (e *BarValidationError) Error() string {
	return fmt.Sprintf("%v: %v", e.field, e.message)
}
